version: "3"
services:
  front:
    build: ./projects/bird_healthcare_frontend/
    command: yarn start
    ports:
      - "$FRONTEND_SERVER_PORT:3000"
    volumes:
      - ./projects/bird_healthcare_frontend/:/myapp/frontend
      - modules:/bird_healthcare/modules
    stdin_open: true
  back:
    build: ./projects/bird_healthcare_backend/
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./projects/bird_healthcare_backend/:/myapp/backend
      - bundle:/bird_healthcare/bundle
    hostname: backend-api
    ports:
      - "$BACKEND_SERVER_PORT:3000"
    environment:
      - BUNDLE_PATH=/bird_healthcare/bundle
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_PORT=$DATABASE_PORT
    depends_on:
      - postgres
    tty: true
    stdin_open: true
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - postgresql-data:/var/lib/postgresql
    ports:
      - "$DATABASE_PORT:5432"
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - LC_COLLATE=C
      - LC_CTYPE=C
      - LC_MESSAGES=C
      - LC_MONETARY=C
      - LC_NUMERIC=C
      - LC_TIME=C
volumes:
  modules:
  bundle:
  postgresql-data:
